# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/CodeFactory/RV-052B-P/RV-052B-Git/RISCV-Code/RV052B/RV052B.srcs/sources_1/ip/fmul/fmul.xci
# IP: The module: 'fmul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/CodeFactory/RV-052B-P/RV-052B-Git/RISCV-Code/RV052B/RV052B.srcs/sources_1/ip/fmul/fmul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmul'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/CodeFactory/RV-052B-P/RV-052B-Git/RISCV-Code/RV052B/RV052B.srcs/sources_1/ip/fmul/fmul.xci
# IP: The module: 'fmul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/CodeFactory/RV-052B-P/RV-052B-Git/RISCV-Code/RV052B/RV052B.srcs/sources_1/ip/fmul/fmul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fmul'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
